#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue May 12 21:31:35 CEST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 725004e8513049da98cb56104220baf0 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot median_filter_tb_behav xil_defaultlib.median_filter_tb -log elaborate.log"
xelab -wto 725004e8513049da98cb56104220baf0 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot median_filter_tb_behav xil_defaultlib.median_filter_tb -log elaborate.log

